# Jekyll Resume Theme

# Site settings
title: Honey Butter Code
email: email@domain.com
description: A code portfolio of pleasant projects.
baseurl: ""
url: ""
name: Zipac
projects: jobplaceholder
location: UK
languages: HTML, CSS and Javascript
github_username:  zipac


# Build settings
markdown: kramdown
